config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :artists do
      member do
        get 'home'
        get 'local_filters'
        post 'local_filters'     
      end
      resources :works
  end

  resources :locals do
    member do
      get 'home'
      post 'artist_filters'
      get 'artist_filters'
    end
  end

  root to: 'site#home', as: :home

  get '/que_es_tuarte' => 'site#que_es_tuarte', as: :que_es_tuarte
  get '/sign_up' => 'site#sign_up', as: :sign_up

end

app/models/local.rb
class Local < ActiveRecord::Base
	belongs_to :user
	delegate :name, to: :user
	attr_accessor :stars


	TYPE_OF_LOCALS = [["Galería", "Galería"], ["Museo", "Museo"], ["Café Temático", "Café Temático"],
					  ["Centro Cultural / Fundación ", "Centro Cultural / Fundación "],
					  ["Centro Educativo", "Centro Educativo"],["Otros", "Otros  "]]

	TYPE_OF_ARTISTS = [["Fotografía","Fotografía"],["Pintura ","Pintura "],["Escultura ","Escultura "],
					   ["Arquitectura","Arquitectura"], ["Artes Visuales","Artes Visuales"]]

	TYPE_OF_PROFESSIONALS = [["Consagrados","Consagrados"], ["Noveles","Noveles"], ["Amateurs","Amateurs"]]

	TYPE_OF_EXPOSITIONS =[["Un único artista", "Un único artista"],["Varios artistas", "Varios artistas"]]

	TYPE_OF_AGREEMENTS = [["Alquiler del local","Alquiler del local"],["Comisión de venta" , "Comisión de venta"]]

  

    def to_param
    	"#{id}-#{name.to_s.parameterize}"
    end


	def calculate_stars_for_artist(artist)
	    @stars = 0
	    @stars += 1 if shows == artist.you_are
	    @stars += 1 if you_are == artist.type_of_locals
	    @stars += 1 if type_of_professional == artist.type_of_professional
	    @stars += 1 if agreements == artist.agreements_with_locals
	    @stars += 1 if type_of_exposition == artist.type_of_expositions
	    self
	end


	def my_artists
		Rails.cache.fetch("artist::#{self.id}::my_locals", :expires_in => 1.day) do
		    artists = Artist.all.map do |artist|
		      artist.calculate_stars_for_local(self)
		    end
		    artists.sort_by { |a| a.stars }.reverse
		end
	end

	
	def filter_for_artists(show, province)
		Artist.joins(:user).where("artists.you_are = :show and users.address like :address", 
						show: show, address: '%' + province + '%')
	end

end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController

	before_action :load_local, only: [:update, :show, :edit, :artist_filters]

	layout "local"	

	def new
		@artist = Artist.new(user_id: current_user.id)
	end

	def create
		@local = current_user.create_local(local_params)
	end

	def show
	end

	def edit
	end

	def update
		if @local.update_attributes(local_params)
			redirect_to local_path(@local)
		else
			render 'edit'
		end
	end

	def home
	end
		    
	def artist_filters
		@artists = @local.filter_for_artists(params[:you_are], params[:province])
	end


	private

	def load_local
		@local = current_user.local
	end

	def local_params
		params.require(:local).permit(:you_are,:shows, :type_of_professional, :type_of_exposition, :agreements)
	end

end

app/helpers/locals_helper.rb
module LocalsHelper
	def link_to_rrss(rrss,index)
		types = {
					0 => ['flaticon-twitter', 'https://twitter.com/intent/user?screen_name='],
					1 => ['flaticon-facebook2', 'https://www.facebook.com/'],
					2 => ['flaticon-instagram13', 'https://www.instagram.com/'],
					3 => ['flaticon-pinterest11', 'https://www.pinterest.com/'],
					4 => ['flaticon-googleplus2', 'https://plus.google.com/']
				}	
		type = types[index]	
	    link_to "<i class='#{type[0]}'></i>".html_safe, "#{type[1]}=#{rrss}" if rrss.present?
	end	
end

app/views/locals/_form.html.erb
   <%= form_for local do |f| %>

		<div >
	        <%= f.label :you_are, "Eres *" %>
			<p class="form_input"><%= f.select(:you_are, options_for_select(Local::TYPE_OF_LOCALS)) %></p>
      	</div>

      	<div >
	        <%= f.label :shows, "Expones *" %>
			<p class="form_input"><%= f.select(:shows, options_for_select(Local::TYPE_OF_ARTISTS)) %></p>
      	</div>


		<div >
	        <%= f.label  :type_of_professional, "Tipo de profesionales que frecuentan tus espacios *" %>
	        <p class="form_input"><%=  f.select(:type_of_professional, options_for_select(Local::TYPE_OF_PROFESSIONALS)) %></p>
      	</div>

      	<div >
	        <%= f.label :type_of_exposition, "Tipo de exposiciones *" %>
	        <p class="form_input"><%=  f.select(:type_of_exposition, options_for_select(Local::TYPE_OF_EXPOSITIONS)) %></p>
      	</div>

      	<div >
	        <%= f.label :agreements,  "Acuerdos con tus artistas *" %>
	       <p class="form_input"> <%=  f.select(:agreements, options_for_select(Local::TYPE_OF_AGREEMENTS)) %></p>
      	</div>

      	<div class="btton_register button-sumit">
      	  	<%= submit_tag "Finalizar" %>
      	</div>

	<% end %>

	

app/views/locals/_private_header.html.erb
<header>
	<strong><%= link_to "tuarte", home_local_path %> </strong>
		<ul class="navigation">
			<li> <strong> <%= current_user.name %> </strong> </li>
			<li> <%= link_to "Edita tu perfil" ,  edit_user_registration_path %></li>
			<li> <%= link_to "Cerrar Sesión", destroy_user_session_path %> </li>
		</ul>
</header>

app/views/locals/_public_header.html.erb
<header>
	<span> <%= link_to "tuarte", home_path %> </span>
		<ul class="navigation">
			<li> <%= link_to "Volver", :back %> </li>
		</ul>
</header>

app/views/locals/_show_local_information.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

 <div id='main'>

    <article>	
		<h4 class="center"> <strong > ESTOS SON LOS ARTISTAS QUE MEJOR SE ADAPTAN A TUS NECESIDADES </strong></h4>
		<br>
		<% if current_user.local.present? %>
			<% current_user.local.my_artists.each do |artist|%>
				<% if artist.stars > 0 %>
					<ul class="flex-container border-container">
						<li class="flex-artist"> 
							<p class ="item-media" style="width:75px;"> <%= image_tag artist.user.avatar.url(:thumb) %> </p>
							<div class="item-txt ">
								<h3> <%= artist.you_are %> 
								<% artist.stars.times do %>
									<i class="flaticon-favourites7"></i>
								<% end %>
								<% if artist.stars<=5 %>
									<%(5-artist.stars).times do %>
										<i class="flaticon-favourites-grey"></i>
									<% end %> 
								<% end %>
								</h3> 
								<h4> <%= artist.user.name %> </h4>
								<p>  <strong>Biografía: </strong><%= artist.user.biography %></p> 
								<p> <%= link_to "Ver más" , artist_path(artist) %></p>	
							</div>
						</li>
					</ul>
				<% end %> 
			<% end %> 
		<% end %> 	
    </article>

    
    <nav>
  		<p class="user user-home">  <%= image_tag current_user.avatar.url(:medium) %> </p> 	
    </nav>

    <aside >
    <p style="border-bottom: 1px solid grey; "> ESTOY BUSCANDO... </p>  
		<%= form_tag (artist_filters_local_path) do %>

				<div class="my_field">
				    <%= label_tag 'you_are', 'Un artista:' %>
					<%= select_tag 'you_are', options_for_select(Artist::TYPE_OF_ARTISTS) %>
				</div>

				<div class="my_field" id="provinces">
				 	<% current_user.get_provinces %>
			        <%= label_tag "province","En la provincia de:" %>
			        <%= select_tag "province" , options_for_select(User::PROVINCES)%>
			     </div>
				 
				 <div class="btton_register">
      	  			<%= submit_tag "Buscar" %>
      			 </div>
		<% end %>					
    </aside>
 </div>

app/views/locals/artist_filters.html.erb
<%= render '/artists/private_header' %>

<div id='main'>
<article>
	<% if @artists.blank? %>
		<p> Lo sentimos, en este momento no existen coincidencias en nuestra base de datos.</p>
		<p> ¡Inténtalo de nuevo con otros parámetros de búsqueda!</p>
		<p> ¡Gracias! </p>
	<% else %>
		<% @artists.each do |artist| %>
			<section class="clearfix">
				<div class="item-local">
					<section class="clearfix">
						<div class="item-local">
							<p class ="item-media"><%=image_tag artist.user.avatar.url(:thumb) %> </p>
							<div class="item-txt ">
								<h3><strong><%=artist.you_are%></strong> - <%=artist.user.name %></h3><p> <%= artist.user.address%> </p>
								<p> <%=artist.user.biography %><%=link_to "Ver más", artist_path(artist) %></p>
							</div>
						</div>
					</section>
				</div>
			</section>			
		<% end %>
	<% end %> 
</article>
<nav ></nav>
<aside></aside>
</div>

app/views/locals/create.html.erb
<%= render "form", local: @local %> 

app/views/locals/edit.html.erb
<%= render '/locals/private_header' %>

<div id='main'>	
	<article>
	    <p>EDITA TU PERFIL EN <strong> TUARTE </strong> </p>
	    <p><small> Todos los campos marcados con * son obligatorios </small></p>
		<%= render 'form', local: @local %> 	
	</article>

	<nav ></nav>
	<aside></aside>
</div>

app/views/locals/home.html.erb
<%= render '/locals/private_header' %>
<% if current_user.name.blank? %>
	<%= render '/users/first_time_you_come_in' %>
<% elsif  current_user.local.you_are.present? %>
	<%= render '/locals/show_local_information' %>
<% end %>

app/views/locals/new.html.erb
<article class = "article-register">
    <p>REGÍSTRATE EN <strong> TUARTE </strong> </p>
    <p><small> Todos los campos marcados con * son obligatorios </small></p>
	<%= render "form", local: @local %> 
</article>

app/views/locals/show.html.erb
<% if @local == current_user.local %>
	<%= render '/locals/private_header' %>
<% else %>
	<%= render '/locals/public_header' %>
<% end %>


<div id='main'>
<article>
	<% local = Local.find params[:id] %>
		<div class="item-local">
			<p class ="item-media" style="margin-top: 60px;"> <%= image_tag local.user.avatar.url(:medium) %> </p>
				<div class="item-show">
					<h3> <strong>  <%= local.you_are%></strong> de <%= local.user.name %> </h3> 
					<p> <strong> Biografía: </strong><%= local.user.biography %></p> 
					<p> <strong> Persona de contacto: </strong><%= local.user.contact_person %> </p>
					<p> <strong> Teléfono: </strong><%= local.user.phone_number %> </p>
					<p> <strong> Dirección: </strong><%= local.user.address %> </p>
					<ul>
						<% if local.user.contact_person.present? %>
							<li> <%= link_to "Página web",  local.user.web %></li>
						<% end %>
						<% local.user.rrss.each_with_index do |rrss,index| %>
							<li><%= link_to_rrss(rrss, index) %>
						<% end %>	
					</ul>
				</div>
		</div>
</article>
	<nav ></nav>
    <aside></aside>
</div>