config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :artists do
      member do
        get 'home'
        get 'local_filters'
        post 'local_filters'     
      end
      resources :works
  end

  resources :locals do
    member do
      get 'home'
      post 'artist_filters'
      get 'artist_filters'
    end
  end

  root to: 'site#home', as: :home

  get '/que_es_tuarte' => 'site#que_es_tuarte', as: :que_es_tuarte
  get '/sign_up' => 'site#sign_up', as: :sign_up

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	belongs_to :user
	has_many :works
	attr_accessor :stars
	delegate :name, to: :user

	TYPE_OF_ARTISTS = [["Fotógrafo", "Fotografía"], ["Pintor", "Pintura"], ["Escultor", "Escultura"], 
						["Arquitecto","Arquitectura" ], ["Realizas videoarte", "Artes Visuales"]]

	TYPE_OF_PROFESSIONALS = [["Profesional consagrado", "Consagrados"],["Profesional novel", "Noveles"],["Amateur","Amateurs"]]

	TYPE_OF_LOCALS = [["Galerías", "Galería"], ["Museos", "Museo"], ["Cafés Temáticos", "Café Temático"],
					  ["Centros Culturales / Fundaciones", "Centro Cultural / Fundación"],
					  ["Centros Educativos", "Centro Educativo"], ["Otros", "Otros"]]

    TYPE_OF_AGREEMENTS = [["Sólo para alquiler","Alquiler del local"],["Con comisión de venta" , "Comisión de venta"]]

    TYPE_OF_EXPOSITIONS = [["Individuales", "Un único artista"],["En compañía de otros artistas", "Varios artistas"]]


    def to_param
    	"#{id}-#{name.to_s.parameterize}"	
    end	

    def calculate_stars_for_local(local)
	    @stars = 0
	    @stars += 1 if you_are == local.shows
	    @stars += 1 if type_of_locals == local.you_are
	    @stars += 1 if type_of_professional == local.type_of_professional
	    @stars += 1 if agreements_with_locals == local.agreements
	    @stars += 1 if type_of_expositions == local.type_of_exposition
	    self
  	end

  	def my_locals
  		Rails.cache.fetch("local::#{self.id}}::my_artists", :expires_in => 1.day) do
    		locals = Local.all.map do |local|
	      		local.calculate_stars_for_artist(self)
	    	end
	    locals.sort_by { |a| a.stars }.reverse
  		end
	end


	def filter_for_locals(show, province)
		Local.joins(:user).where("locals.you_are = :show and users.address like :address", 
					show: show, address: '%' + province + '%')
	end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

	before_action :load_artist, only: [:update, :edit, :local_filters]

	layout "artist"
	
	def new
		@artist = Artist.new(user_id: current_user.id)	
	end

	def create
		@artist = current_user.create_artist(artist_params)
	end

	def show
		@artist = Artist.find params[:id]
	end

	def edit
	end

	def update
		if @artist.update_attributes(artist_params)
			redirect_to artist_path(@artist)
		else
			render 'edit'
		end
	end

	def home
	end

	def local_filters
		@locals = @artist.filter_for_locals(params[:shows], params[:province])
	end


	private

	def load_artist
		@artist = current_user.artist
	end


	def artist_params
		params.require(:artist).permit(:you_are, :type_of_professional, :type_of_locals, :agreements_with_locals, :type_of_expositions)
	end

end

app/helpers/artists_helper.rb
module ArtistsHelper
	def link_to_rrss(rrss,index)
		types = {
					0 => ['flaticon-twitter', 'https://twitter.com/intent/user?screen_name='],
					1 => ['flaticon-facebook2', 'https://www.facebook.com/'],
					2 => ['flaticon-instagram13', 'https://www.instagram.com/'],
					3 => ['flaticon-pinterest11', 'https://www.pinterest.com/'],
					4 => ['flaticon-googleplus2', 'https://plus.google.com/']
				}	
		type = types[index]	
	    link_to "<i class='#{type[0]}'></i>".html_safe, "#{type[1]}=#{rrss}" if rrss.present?
	end	

end

app/views/artists/_form.html.erb
<article>

	<%= form_for artist do |f| %>

		<div>
		    <%= f.label :you_are, "Eres *" %>
			<p class="form_input"><%= f.select(:you_are, options_for_select(Artist::TYPE_OF_ARTISTS)) %></p>
		</div>

		<div>
		    <%= f.label :type_of_professional, "Tipo de profesional *" %>
			<p class="form_input"><%= f.select(:type_of_professional, options_for_select(Artist::TYPE_OF_PROFESSIONALS)) %></p>
		</div>

		<div>
		    <%= f.label :type_of_locals, "Lugares en los que sueles exponer *" %>
			<p class="form_input"><%= f.select(:type_of_locals, options_for_select(Artist::TYPE_OF_LOCALS)) %></p>
		</div>

		<div>
		    <%= f.label :agreements_with_locals, "Te interesaría un local *" %>
			<p class="form_input"><%= f.select(:agreements_with_locals, options_for_select(Artist::TYPE_OF_AGREEMENTS)) %></p>
		</div>

		<div>
		    <%= f.label :type_of_expositions, "Te gusta que tus exposiciones sean *" %>
			<p class="form_input"><%= f.select(:type_of_expositions, options_for_select(Artist::TYPE_OF_EXPOSITIONS)) %></p>
		</div>

      	<div class="btton_register button-sumit">
      	  	<%= f.submit"Finalizar" %>
      	</div>


	<% end %>

</article>

app/views/artists/_modal.html.erb
<div id="myModal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content" style="width: 275px; ">
			<div class="modal-header">
			     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				 <% artist=Artist.find (params[:id]) %>
			     <h4 class="modal-title black-size" id="modal-title">Artista: <%= artist.user.name %></h4>
			     </div>
			        <% if artist.works.present? %>
				        <% artist.works.each do |work| %>
					        <div class="modal-body" id="modal-body">
					            <p class ="item-media-modal " > <%= image_tag work.avatar.url(:thumb) %></p>
					            <p class="black-size"><%= work.title %></p>
					        </div>
					        <div class="additional-information black-size" id="additional-information">
					            <p style="font-size: 17px;">
					            <strong>Dimensiones: </strong><small><%= work.size %>cm </small>
					            </p>
				                <p style="font-size: 17px;"><strong> Precio: </strong><small><%= work.price %>€</small></p> 
				            </div>
				        <% end %>
				    <%end%>
			     <div class="modal-footer">
			     <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

app/views/artists/_private_header.html.erb
<header > 
	<span ><strong> <%= link_to "tuarte", home_artist_path %> </strong></span>
	<ul class="navigation">
		<li> <strong> <%= current_user.name %> </strong> </li>
		<li> <%= link_to "Edita tu perfil" ,  edit_user_registration_path %></li>
		<li> <%= link_to "Cerrar Sesión", destroy_user_session_path %> </li>
	</ul>
</header>

app/views/artists/_public_header.html.erb
<header>
	<span> <%= link_to "tuarte", home_path %> </span>
	<ul class="navigation">
		<li> <%= link_to "Volver", :back %> </li>
	</ul>
</header>

app/views/artists/_show_artist_information.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

 <div id='main'>

    <article>	
	<h4 class="center"> <strong > ESTOS SON LOS ESPACIOS QUE MEJOR SE ADAPTAN A TUS NECESIDADES </strong></h4>
	<br>
	<% if current_user.artist.present? %>

		<% current_user.artist.my_locals.each do |local|%>
		
			<% if local.stars > 0 %>

				<ul class="flex-container border-container">
					<li class="flex-artist"> 
						<p class ="item-media" style="width: 175px;"> <%= image_tag local.user.avatar.url(:thumb) %> </p>
						<div class="item-txt ">
							<h3> <%= local.you_are %> 
								<% local.stars.times do %>
									<i class="flaticon-favourites7"></i>
								<% end %>
								<% if local.stars<=5 %>
									<%(5-local.stars).times do %>
										<i class="flaticon-favourites-grey"></i>
									<% end %> 
								<% end %>
							</h3> 
							<h4> <%= local.user.name %> </h4>
							<p> <strong>Biografía: </strong> <%= local.user.biography %></p> <p> <%= link_to "Ver más" , local_path(local) %></p>
						</div>		
					</li>
				</ul>

			<% end %> 
		<% end %> 
	<% end %> 	
    </article>


    <nav>
	    <% if params[:controller]=="works" && params[:action]=="create" %>
			<%= render '/layouts/work_added' %>
	  	<% end %>

	  	<p class="user user-home">  <%= image_tag current_user.avatar.url(:medium) %> </p> 
		<p class="add-work";>
				<%= link_to "Añade una de tus Obra", new_artist_work_path(current_user.artist) if current_user.artist.present?%> 
	    </p>
		<br>
		<p> <% if current_user.artist.works.present?%>
				<a href="#myModal" class="add-work" data-toggle="modal" style="color: white;text-decoration: none;"> 
				    Listado de mis Obra</a>
			<% end %>
		</p> 	
    </nav>


    <aside >
    <p style="border-bottom: 1px solid grey; "> ESTOY BUSCANDO... </p>  
		<%= form_tag (local_filters_artist_path) do %>

			 <div >
				<p class="p-aside"> <%= label_tag 'shows', 'Un espacio para mis obras' %></p>
				<%= select_tag 'shows', options_for_select(Local::TYPE_OF_LOCALS) %>
			</div>

			<div id="provinces">
				<p class="p-aside"> <% current_user.get_provinces %> </p>
				<%= label_tag "province","En la provincia de:" %>
				<%= select_tag "province" , options_for_select(User::PROVINCES)%>
			</div>
						 
			<div class="btton_register">
		      	<%= submit_tag "Buscar" %>
		    </div>

		<% end %>
				
    	
    </aside>

    <div id="myModal" class="modal fade">
		<div class="modal-dialog">
	 		<div class="modal-content" style="width: 275px; ">
			    <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
			        </button>
			        <h4 class="modal-title black-size" id="modal-title">Artista: <%= current_user.name %></h4>
			        </div>
			        <% if current_user.artist.works.present? %>
				        <% current_user.artist.works.each do |work| %>
					        <div class="modal-body" id="modal-body">
					            <p class ="item-media-modal " > <%= image_tag work.avatar.url(:thumb) %></p>
					            <p class="black-size"><%= work.title %></p>
					        </div>
					        <div class="additional-information black-size" id="additional-information">
					            <p style="font-size: 17px;">
				                  	<strong>Dimensiones: </strong><small><%= work.size %>cm </small></p >
				                <p style="font-size: 17px;"><strong> Precio: </strong><small><%= work.price %>€</small></p> 
				            </div>
				        <% end %>
				    <%end%>
			                
			        <div class="modal-footer">
			            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			        </div>
			    </div>
			</div>
		</div>
	</div>

app/views/artists/create.html.erb
<%= render "form", artist: @artist %> 

app/views/artists/edit.html.erb
<%= render '/artists/private_header' %>

<div id='main'>	
	<article>
	    <h1>EDITA TU PERFIL EN <strong> TUARTE </strong> </h1>
	    <p>Todos los campos marcados con * son obligatorios</p>
		<%= render 'form', artist: @artist %> 
	</article>
	<nav></nav>
	<aside></aside>
</div>

app/views/artists/home.html.erb
<%= render '/artists/private_header' %>
<% if @work.present? && @work.new_record? %>
	<%= render '/works/form' %>
<% else %>
	<% if current_user.name.blank? %>
		<%= render '/users/first_time_you_come_in' %>
	<% elsif  current_user.artist.you_are.present?%>
		<%= render '/artists/show_artist_information' %>
	<% end %>
<% end %>

app/views/artists/local_filters.html.erb
<%= render '/artists/private_header' %>
<div id='main'>
<article>
	<% if @locals.empty? %>
		<p> Lo sentimos, en este momento no existen coincidencias en nuestra base de datos.</p>
		<p> ¡Inténtalo de nuevo con otros parámetros de búsqueda!</p>
		<p> ¡Gracias! </p>
	<% else %>
		<% @locals.each do |local| %>
			<section class="clearfix">
				<div class="item-local">
					<section class="clearfix">
						<div class="item-local">
							<p class ="item-media"><%= image_tag local.user.avatar.url(:thumb) %> </p>
							<div class="item-txt ">
								<h3><strong><%=local.you_are%></strong> de <%= local.user.name %></h3> 
								<p> <%= local.user.address%> </p>
								<p>  <%=local.user.biography %><%= link_to "Ver más" , local_path(local) %></p>
							</div>
						</div>
					</section>
				</div>
			</section>			
		<% end %>
	<% end %> 
</article>

 <nav></nav>
 <aside></aside>
</div>

app/views/artists/new.html.erb
<article class = "article-register">
    <p>REGÍSTRATE EN <strong> TUARTE </strong> </p>
    <p><small> Todos los campos marcados con * son obligatorios </small></p>
	<%= render 'form', artist: @artist %> 
</article>

app/views/artists/show.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

<% if @artist == current_user.artist %>
	<%= render '/artists/private_header' %>
<% else %>
	<%= render '/artists/public_header' %>
<% end %>
<div id='main'>	
<article>
	<section class="clearfix">
		<div class="item-local">
		<% artist = Artist.find params[:id] %>
			<p class ="item-media" style="margin-top: 60px;"> <%= image_tag @artist.user.avatar.url(:medium) %> </p>
			<div class="item-show">
				<h3> <strong>  <%= @artist.you_are%></strong> - <%= @artist.user.name %> </h3> 
				<p> <strong> Biografía: </strong><%= @artist.user.biography %></p> 
				<p> <strong> Persona de contacto: </strong><%= @artist.user.contact_person %> </p>
				<p> <strong> Teléfono: </strong><%= @artist.user.phone_number %> - 
				    <strong> Email: </strong><%= @artist.user.email %></p>
				<p> <strong> Dirección: </strong><%= @artist.user.address %>
				
				<% if @artist.works.present?%>
			  			<a href="#myModal" class="button" data-toggle="modal" 
			  			style="color: white;text-decoration: none;"> Listado de mis Obra</a>
			    <% end %>
				 </p>
				<ul>
					<% if @artist.user.contact_person.present? %>
						<li> <%= link_to "Página web",  @artist.user.web %></li>
					<% end %>
					<% @artist.user.rrss.each_with_index do |rrss,index| %>
						<li><%= link_to_rrss(rrss, index) %>
					<% end %>

				</ul>
				
			</div>
		</div>
	</section>

<%= render 'modal' %>

</article>
 <nav ></nav>
 <aside></aside>
</div>