config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :artists do
      member do
        get 'home'
        get 'local_filters'
        post 'local_filters'     
      end
      resources :works
  end

  resources :locals do
    member do
      get 'home'
      post 'artist_filters'
      get 'artist_filters'
    end
  end

  root to: 'site#home', as: :home

  get '/que_es_tuarte' => 'site#que_es_tuarte', as: :que_es_tuarte
  get '/sign_up' => 'site#sign_up', as: :sign_up

end

app/views/layouts/_show_artist_information.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>


  <% if params[:controller]=="works" && params[:action]=="create" %>
		<%= render '/layouts/work_added' %>
  <% else %>

		  <p class="user">  <%= image_tag current_user.avatar.url(:medium) %> 
		  		<span class="button"> <%= link_to "Añadir una Obra", new_artist_work_path(current_user.artist) if !current_user.artist.nil?%> </span>
				<% if !current_user.artist.works.empty?%>
			  			<a href="#myModal" class="button" data-toggle="modal" 
			  			style="color: white;text-decoration: none;"> Listado de mis Obra</a>
			    <% end %>
		  </p>

		  <div class="clearfix">

			<aside class="my_aside">
				<p> ESTOY BUSCANDO... </p>  
				

				<div class="my_field">
					<%= form_tag (local_filters_artist_path) do %>

						  <div class="my_field">
						    <%= label_tag 'shows', 'Un espacio para mis obras' %>
							<%= select_tag 'shows', options_for_select(Local::TYPE_OF_LOCALS) %>
						</div>

						<div class="my_field" id="provinces">
						 	<% current_user.get_provinces %>
					        <%= label_tag "province","En la provincia de:" %>
					        <%= select_tag "province" , options_for_select(User::PROVINCES)%>
					     </div>
						 
						  <div class="btton_register">
		      	  			<%= submit_tag "Buscar" %>
		      			  </div>

					<% end %>
				</div>

			</aside>

			<section class="my_section">
			
				<% if !current_user.artist.nil? %>
						<% stars = current_user.artist.my_locals.values %>
						<% ids = current_user.artist.my_locals.keys %>
						<% i = 0 %> 
						<% ids.each do |id|%>
							<%local = Local.find id %>

								<section class="clearfix">
									<div class="item-local">
											<p class ="item-media" > <%= image_tag local.user.avatar.url(:thumb) %> </p>
											<div class="item-txt ">
												<h3> <%= local.user.name %>  
												<% stars[i].times do %>
													<i class="flaticon-favourites7"></i>
												<% end %>
												</h3> 
												<p>  <%= local.user.biography %></p> <p> <%= link_to "Ver más" , local_path(local) %></p>
											</div>
									</div>
								</section>
					    <% i+= 1 %>
					    <% end %> 
				<% end %>
			
			</section>

		</div>

		<div id="myModal" class="modal fade">
			        <div class="modal-dialog">
			            <div class="modal-content">
			                <div class="modal-header">
			                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
			                    </button>
			                    <h4 class="modal-title" id="modal-title">Artista: <%= current_user.name %></h4>
			                </div>
			                <% current_user.artist.works.each do |work| %>
				                <div class="modal-body" id="modal-body">
				                <p class ="item-media" > <%= image_tag work.avatar.url(:thumb) %> </p>
				                    <p><%= work.title %></p>
				                </div>
				                <div class="additional-information" id="additional-information">
				                <ul>
			                    	<li>Dimensiones: <small><%= work.size %>cm </small></li>
			                    	<li>Precio: <small><%= work.price %>€</small></li> 
			                    </ul>
			                </div>
			                <% end %>
			                
			                <div class="modal-footer">
			                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			                </div>
			            </div>
			        </div>
		</div>
<% end %>

app/views/layouts/_show_local_information.html.erb
<p class="user"> <%= image_tag current_user.avatar.url(:medium) %> </p>
<%#= @local.you_are %>

<div class="clearfix">

	<aside class="my_aside">
		<p> ESTOY BUSCANDO... </p>

		<div class="my_field">
			<%= form_tag (artist_filters_local_path) do %>

				  <div class="my_field">
				    <%= label_tag 'you_are', 'Un artista:' %>
					<%= select_tag 'you_are', options_for_select(Artist::TYPE_OF_ARTISTS) %>
				</div>

				<div class="my_field" id="provinces">
				 	<% current_user.get_provinces %>
			        <%= label_tag "province","En la provincia de:" %>
			        <%= select_tag "province" , options_for_select(User::PROVINCES)%>
			     </div>
				 
				  <div class="btton_register">
      	  			<%= submit_tag "Buscar" %>
      			  </div>

			<% end %>
		</div>

	</aside>

	<section class="my_section">
	<ul>
		<% if current_user.local.present? %>			
			<% stars = current_user.local.my_artists.values %>
			<% ids = current_user.local.my_artists.keys %>
			<% i = 0 %> 
			<% ids.each do |id|%>
				<%artist = Artist.find id %>

					<section class="clearfix">
						<div class="item-local">
								<p class ="item-media" > <%= image_tag artist.user.avatar.url(:thumb) %> </p>
								<div class="item-txt ">
									<h3> <%= artist.user.name %>  
									<% stars[i].times do %>
										<i class="flaticon-favourites7"></i>
									<% end %>
									</h3> 
									<p>  <%= artist.user.biography %></p> <p> <%= link_to "Ver más" , artist_path(artist) %></p>
								</div>
						</div>
					</section>
		    <% i+= 1 %>
		    <% end %> 

		<% end %>
	</section>

</div>



	    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">

	<head>
		  <meta charset="UTF-8">
		  <meta name="viewport" content="width=device-width, initial-scale=1">

		  <title>tuarte</title>

		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
	</head>

	<body>


	<header > 
		<span >
			<strong> <%= link_to "tuarte", home_path %> </strong>
		</span>
		<ul class="navigation">
			  <li><%= link_to "¿Qué es <strong>tuarte</strong>?".html_safe, que_es_tuarte_path %> </a></li>
			  <li><%= link_to "Regístrate" , sign_up_path %></li>
			  <li><%= link_to "Inicia Sesión", new_user_session_path %></li>
		</ul>

 	</header>

	<div id='main'>

	    <article> 
			<%= yield %>
		</article>

	    <nav ></nav>
    
    	<aside></aside>
 	</div>
		
	<footer>
		©COPYRIGHT 2015. LORENA - IRONHACK. TODOS LOS DERECHOS RESERVADOS
	</footer>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

	</body>

</html>

app/views/layouts/artist.html.erb
<html lang="es">

	<head>
		  <meta charset="UTF-8">
		  <meta name="viewport" content="width=device-width, initial-scale=1">

		  <title>tuarte</title>

		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= yield %>

		<footer>
			©COPYRIGHT 2015. LORENA - IRONHACK. TODOS LOS DERECHOS RESERVADOS
		</footer>
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

	</body>

</html>

app/views/layouts/edit_profile.html.erb
<!DOCTYPE html>
<html lang="es">

	<head>
		  <meta charset="UTF-8">
		  <meta name="viewport" content="width=device-width, initial-scale=1">

		  <title>tuarte</title>

		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>

		  <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
		  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&sensor=false"></script>
	</head>

	<body>
		
		<header > 
			<span >
				<strong> <%= link_to "tuarte", home_path %> </strong>
			</span>
			<ul class="navigation">
				  <li> <strong> <%= current_user.name if current_user.present?%> </strong> </li>
				<li> <%= link_to "Cerrar Sesión", destroy_user_session_path %> </li>
			</ul>

 		</header>


		<div id='main'>

		    <article> 
				<%= yield %>
			</article>

		    <nav ></nav>
	    
	    	<aside></aside>
 		</div>


		<footer>
			©COPYRIGHT 2015. LORENA - IRONHACK. TODOS LOS DERECHOS RESERVADOS
		</footer>

	</body>

</html>

app/views/layouts/local.html.erb
<!DOCTYPE html>
<html lang="es">

	<head>
		  <meta charset="UTF-8">
		  <meta name="viewport" content="width=device-width, initial-scale=1">

		  <title>tuarte</title>

		  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		  <%= csrf_meta_tags %>
	</head>

	<body>
	
		<%= yield %>
	
		<footer>
			©COPYRIGHT 2015. LORENA - IRONHACK. TODOS LOS DERECHOS RESERVADOS
		</footer>

	</body>

</html>